# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MmYSFwry9DAhZbcxf6D78BZilHeZobc0
"""

import tweepy
import ml

client = tweepy.Client(bearer_token='AAAAAAAAAAAAAAAAAAAAAGr9hQEAAAAApYgTuc9DqLffRiZzJXqssJndaGg%3D1gH5uqhTJ9jJV54Cx9KZhB9Cop2qY4dgOtbwgR87YXWqXJNXO3')


# Replace with your own search query
query = 'ipl -is:retweet'

# Replace the limit=1000 with the maximum number of Tweets you want
for tweet in tweepy.Paginator(client.search_recent_tweets, query=query,
                              tweet_fields=['context_annotations', 'created_at'], max_results=100).flatten(limit=4):
    print(tweet.id)
    print(tweet)
    print(ml.function_1(tweet.text))